
import { firebaseConfig } from '../assets/js/firebase-config.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getAuth, signInWithEmailAndPassword, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc, addDoc, collection, getDocs, deleteDoc, serverTimestamp, query, orderBy } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);const $=id=>document.getElementById(id),v=id=>($(id)?.value||'').trim(),num=id=>Number(v(id).replace(/,/g,''))||0;const projectFields=['title','description','budget','spent','percentOverride','image1','image2','status','projectUpdatedAtText'];
function msg(t,ok=true){const el=$('status');el.textContent=t;el.className='status '+(ok?'ok':'err');setTimeout(()=>{el.className='status'},3500)}function setBusy(btn,text='กำลังบันทึก...'){btn.classList.add('pressed');btn.disabled=true;const old=btn.textContent;btn.textContent=text;return()=>{btn.classList.remove('pressed');btn.disabled=false;btn.textContent=old}}
function fmt(x){const n=Number(String(x??'').replace(/,/g,''));return Number.isFinite(n)&&String(x??'')!==''?n.toLocaleString('en-US'):''}['bank1Amount','bank2Amount','cashAmount','budget','spent','percentOverride'].forEach(id=>$(id)?.addEventListener('blur',()=>{$(id).value=fmt($(id).value)}));
onAuthStateChanged(auth,async u=>{$('loginBox').style.display=u?'none':'block';$('adminBox').style.display=u?'block':'none';if(u)await loadAll()});$('loginBtn').onclick=()=>signInWithEmailAndPassword(auth,v('email'),v('password')).catch(e=>msg('เข้าไม่ได้: '+e.message,false));$('logoutBtn').onclick=()=>signOut(auth);
['abbotImage','qrImage','image1','image2'].forEach(id=>$(id)?.addEventListener('input',()=>preview(id,id+'Preview')));function preview(a,b){const url=v(a),img=$(b);if(url){img.src=url;img.style.display='block'}else img.style.display='none'}async function loadDoc(path,map){const s=await getDoc(doc(db,...path));if(!s.exists())return;const x=s.data();for(const [field,id] of Object.entries(map)){if($(id))$(id).value=x[field]??''}}async function loadAll(){await loadDoc(['settings','site'],{templeName:'templeName',address:'address',phone:'phone',facebookUrl:'facebookUrl',abbotImage:'abbotImage',abbotCaption:'abbotCaption'});await loadDoc(['finance','balances'],{bank1Name:'bank1Name',bank1Amount:'bank1Amount',bank2Name:'bank2Name',bank2Amount:'bank2Amount',cashAmount:'cashAmount',updatedAtText:'balanceUpdatedAtText'});await loadDoc(['finance','donate'],{qrImage:'qrImage',accountName:'accountName',accountNumber:'accountNumber',bankName:'bankName',note:'note'});['bank1Amount','bank2Amount','cashAmount'].forEach(id=>$(id).value=fmt($(id).value));['abbotImage','qrImage'].forEach(id=>preview(id,id+'Preview'));await loadProjects()}
$('saveSettings').onclick=async e=>{const done=setBusy(e.currentTarget);try{await setDoc(doc(db,'settings','site'),{templeName:v('templeName'),address:v('address'),phone:v('phone'),facebookUrl:v('facebookUrl'),abbotImage:v('abbotImage'),abbotCaption:v('abbotCaption'),updatedAt:serverTimestamp()},{merge:true});msg('บันทึกข้อมูลวัดแล้ว หน้าเว็บจะเปลี่ยนทันที')}catch(err){msg('บันทึกไม่ได้: '+err.message,false)}done()};
$('saveBalances').onclick=async e=>{const done=setBusy(e.currentTarget);try{await setDoc(doc(db,'finance','balances'),{bank1Name:v('bank1Name'),bank1Amount:num('bank1Amount'),bank2Name:v('bank2Name'),bank2Amount:num('bank2Amount'),cashAmount:num('cashAmount'),updatedAtText:v('balanceUpdatedAtText'),updatedAt:serverTimestamp()},{merge:true});msg('บันทึกยอดเงินแล้ว หน้าเว็บจะเปลี่ยนทันที')}catch(err){msg('บันทึกไม่ได้: '+err.message,false)}done()};
$('saveDonate').onclick=async e=>{const done=setBusy(e.currentTarget);try{await setDoc(doc(db,'finance','donate'),{qrImage:v('qrImage'),accountName:v('accountName'),accountNumber:v('accountNumber'),bankName:v('bankName'),note:v('note'),updatedAt:serverTimestamp()},{merge:true});msg('บันทึกข้อมูลบริจาคแล้ว หน้าเว็บจะเปลี่ยนทันที')}catch(err){msg('บันทึกไม่ได้: '+err.message,false)}done()};
$('saveProject').onclick=async e=>{const done=setBusy(e.currentTarget);try{const data={title:v('title'),description:v('description'),budget:num('budget'),spent:num('spent'),percentOverride:v('percentOverride')===''?'':num('percentOverride'),image1:v('image1'),image2:v('image2'),status:v('status'),projectUpdatedAtText:v('projectUpdatedAtText'),updatedAt:serverTimestamp()};const id=v('projectId');if(id){await setDoc(doc(db,'projects',id),data,{merge:true});msg('แก้ไขโครงการแล้ว หน้าเว็บจะเปลี่ยนทันที')}else{await addDoc(collection(db,'projects'),{...data,createdAt:serverTimestamp()});msg('เพิ่มโครงการแล้ว หน้าเว็บจะเปลี่ยนทันที')}clearProject();await loadProjects()}catch(err){msg('บันทึกไม่ได้: '+err.message,false)}done()};
$('clearProject').onclick=clearProject;function clearProject(){$('projectId').value='';projectFields.forEach(id=>$(id).value='');$('image1Preview').style.display='none';$('image2Preview').style.display='none';$('projectMode').textContent='โหมด: เพิ่มโครงการใหม่'}async function getProjects(){try{return await getDocs(query(collection(db,'projects'),orderBy('createdAt','desc')))}catch(e){return await getDocs(collection(db,'projects'))}}async function loadProjects(){const snap=await getProjects();$('projectList').innerHTML=snap.docs.map(d=>{const x=d.data(),p=x.percentOverride!==''&&x.percentOverride!==undefined?Number(x.percentOverride||0):(Number(x.budget)?Number(x.spent||0)/Number(x.budget)*100:0);return`<div class="item">${x.image1?`<img src="${x.image1}" onerror="this.style.display='none'">`:''}<b>${x.title||d.id}</b><p>งบประมาณ ${fmt(x.budget)} / ใช้ไป ${fmt(x.spent)} / ${p.toFixed(1)}%</p><div class="tools"><button class="btn small" onclick="editProject('${d.id}')">แก้ไข</button><button class="btn small danger" onclick="deleteProject('${d.id}')">ลบ</button></div></div>`}).join('')||'<div class="item">ยังไม่มีโครงการ</div>'}
window.editProject=async id=>{const s=await getDoc(doc(db,'projects',id));if(!s.exists())return;const x=s.data();$('projectId').value=id;projectFields.forEach(k=>$(k).value=x[k]??'');['budget','spent','percentOverride'].forEach(k=>$(k).value=fmt($(k).value));preview('image1','image1Preview');preview('image2','image2Preview');$('projectMode').textContent='โหมด: แก้ไขโครงการ';window.scrollTo({top:document.getElementById('projectForm').offsetTop-30,behavior:'smooth'})};window.deleteProject=async id=>{if(confirm('ลบโครงการนี้?')){await deleteDoc(doc(db,'projects',id));msg('ลบโครงการแล้ว');loadProjects()}};
$('seedProjects').onclick=async e=>{const done=setBusy(e.currentTarget,'กำลังสร้าง...');try{const samples=[{title:'โครงการสร้างพระอุโบสถ',description:'พื้นที่ศักดิ์สิทธิ์สำหรับประกอบศาสนพิธีและเป็นศูนย์รวมจิตใจของชุมชน',budget:500000,spent:125000,percentOverride:'',status:'กำลังดำเนินการ',projectUpdatedAtText:'ข้อมูลปัจจุบัน'},{title:'โครงการสร้างกุฏิสงฆ์',description:'ปรับปรุงที่พักสงฆ์ให้เหมาะแก่การปฏิบัติธรรมและการจำพรรษา',budget:250000,spent:75000,percentOverride:'',status:'กำลังดำเนินการ',projectUpdatedAtText:'ข้อมูลปัจจุบัน'},{title:'กองทุนภัตตาหารและค่าน้ำค่าไฟ',description:'ดูแลภัตตาหารและสาธารณูปโภคประจำวัด เพื่อให้กิจของสงฆ์ดำเนินไปได้อย่างเรียบร้อย',budget:120000,spent:30000,percentOverride:'',status:'เปิดรับสนับสนุน',projectUpdatedAtText:'ข้อมูลปัจจุบัน'}];for(const p of samples)await addDoc(collection(db,'projects'),{...p,image1:'',image2:'',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});msg('สร้างโครงการตัวอย่างแล้ว')}catch(err){msg('สร้างไม่ได้: '+err.message,false)}done();loadProjects()};
